const languageOptions = [
    { code: "Arabic_Saudi_Arabia", label: "Arabic (Saudi Arabia)" },
    { code: "Arabic_UAE", label: "Arabic (UAE)" },
    { code: "Bulgarian", label: "Bulgarian" },
    { code: "Chinese", label: "Chinese" },
    { code: "Croatian", label: "Croatian" },
    { code: "Czech", label: "Czech" },
    { code: "Danish", label: "Danish" },
    { code: "Dutch", label: "Dutch" },
    { code: "English_Australia", label: "English (Australia)" },
    { code: "English_Canada", label: "English (Canada)" },
    { code: "English_UK", label: "English (UK)" },
    { code: "English_USA", label: "English (USA)" },
    { code: "Filipino", label: "Filipino" },
    { code: "Finnish", label: "Finnish" },
    { code: "French_Canada", label: "French (Canada)" },
    { code: "French_France", label: "French (France)" },
    { code: "German", label: "German" },
    { code: "Greek", label: "Greek" },
    { code: "Hindi", label: "Hindi" },
    { code: "Hungarian", label: "Hungarian" },
    { code: "Indonesian", label: "Indonesian" },
    { code: "Italian", label: "Italian" },
    { code: "Japanese", label: "Japanese" },
    { code: "Korean", label: "Korean" },
    { code: "Malay", label: "Malay" },
    { code: "Norwegian", label: "Norwegian" },
    { code: "Polish", label: "Polish" },
    { code: "Portuguese_Brazil", label: "Portuguese (Brazil)" },
    { code: "Portuguese_Portugal", label: "Portuguese (Portugal)" },
    { code: "Romanian", label: "Romanian" },
    { code: "Russian", label: "Russian" },
    { code: "Slovak", label: "Slovak" },
    { code: "Spanish_Mexico", label: "Spanish (Mexico)" },
    { code: "Spanish_Spain", label: "Spanish (Spain)" },
    { code: "Swedish", label: "Swedish" },
    { code: "Tamil", label: "Tamil" },
    { code: "Turkish", label: "Turkish" },
    { code: "Ukrainian", label: "Ukrainian" },
    { code: "Vietnamese", label: "Vietnamese" },
];

export default languageOptions;
